# Generated by Django 4.2.11 on 2024-03-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
